### PR TITLE
Create api-interaction.py

### PR DESCRIPTION
**Pull request by leeideal**
## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #35 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.
- Cloud Functions
-  PaLM2

### CODE REVIEW

**Comment by leeideal** [comment]
test

**Comment by wonho1401** [comment]
main으로 PR 날리셨습니다

**Review by HyungJoonSon — CHANGES_REQUESTED** [review]
main 입니다...

**Comment by leeideal** [comment]
띄어어어

**Pull request merged**
