### PR TITLE
⚡ Docs - Update README.md

### PR DESCRIPTION
**Pull request by wonho1401**
## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #51 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- Update README.md

### CODE REVIEW

**Review by leeideal — APPROVED** [review]
공들인 README 작성 수고하셨습니다! 깔끔하고 좋네요

**Review by HyungJoonSon — APPROVED** [review]
리드미 장인...

**Review by shimseohyun — APPROVED** [review]
잘하셨습니다~

**Review by HyungJoonSon — APPROVED** [review]
내용 추가하였습니다.

**Pull request merged**
